### ISSUE TITLE
TODO towards 1.0

### ISSUE THREAD

**Issue by tjhei** [geodynamics/burnman#264]
- [x] 3d seismic model, import to axisem (Sanne)
- [x] mineos output inside BurnMan
- [ ] planet.layer temperature as function (Timo)
- [ ] planet builder with self-consistent conductive/convective profiles (+heat generation)
- [x] liquid iron bug (Bob)
- [x] liquid database (Bob)
- [x] EOS statistics
- [x] Gibbs minimizer
- [x] ASPECT -> seismic data (1d averaged, 2d/3d data)
- [x] pvt statistics (Bob)
