### ISSUE TITLE
TODO technical paper

### ISSUE THREAD

**Issue by tjhei** [geodynamics/burnman#265]
- [ ] updated flowchart with workflows including input/output
- [ ] Ipython pvt fitter
- [ ] planet builder example
- [ ] seismic example (earth->ASPECT->seismic data)
- [ ] phase diagram example (pyrolite?)
