### ISSUE TITLE
Major release (1.0.0)

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#388]
As a companion to the new paper, we should make another major release. In this release, we should add the following:

- [x] Add composition fitting functions (#382) 
- [x] Add polytope stuff (#406)
- [x] Add equilibration functionality (#407)
- [x] Add HP98 EOS (#410)
- [x] Add HP2011, HGP2018 melt phases (based on the HP98 EOS, #410)  
- [x] Add ternary terms to the subregular solution model (#409)
- [x] Add existing examples (#411)
- [x] Add detail to the examples in the manual (#411)
- [x] Mention/describe the contributions and ipython directories (#412)
- [x] Bug fix (#413)
- [x] Add  isentropic to appropriate methods in AnisotropicMaterial (#419)
- [x] Double check that the autogenerated documentation for the code base is complete (#421)
- [x] Restructure the code (#422) 
- [x] Check manual compiles successfully on ReadTheDocs.

Final steps once we have the code ready:
- [x] Open zenodo, start new version, reserve DOI (currently at the top of Basic Information)
- [x] New branch (burnman-Major.Minor)
- [x] Bump version number in new branch (in burnman/version.py)
- [x] Update changelog.txt with major changes since the last release.
- [x] Update setup.py (if necessary, probably only Python versions need checking, but might be worth checking that `sudo python setup.py sdist bdist_wheel` works without errors)
- [x] Update new link to the zenodo version (using the new reserved DOI) in burnman/__init__.py
- [x] Update new link to the zenodo version (using the new reserved DOI) in docs/index.rst
- [x] Update new badge link to zenodo (using the new reserved DOI) in Readme.md
- [x] Push new branch to Github upstream burnman-Major.Minor (*not* master)
- [x] Make release on Github using upstream burnman-Major.Minor branch
- [x] Make release commit (tag, not branch) active on readthedocs (you'll need to build from master first so that ReadTheDocs finds the new release tag)
- [x] Build documentation on readthedocs
- [x] Download zip file
- [x] Upload new zip file to zenodo, fill in details on website (including new link to ReadTheDocs)
- [x] Save and publish in zenodo
- [x] Update GitHub release with new zip files and link to the ReadTheDocs documentation
- [x] Push release to Pypi (from clean directory):
 1) sudo python setup.py sdist bdist_wheel (sudo unfortunately required)
 2) twine check dist/* (to check zip and wheel)
 3) twine upload --repository-url https://test.pypi.org/legacy/ dist/* (to test upload, can get password from the pypi website)
 4) twine upload dist/* (the final upload to Pypi)
- [x] Merge upstream burnman-Major.Minor branch to master
- [x] Bump version numbers in version.py on upstream master 
 - version=[Major].[Minor+1].0pre
 - short_version=[Major].[Minor+1].0
- [x] Check and update homepage (especially the downloads section and the zenodo links)
