### ISSUE TITLE
BurnMan release checklist

### ISSUE THREAD

**Issue by bobmyhill** [geodynamics/burnman#434]
This checklist should be completed for every release of BurnMan

- [ ] Check new version can be used non-locally (`python -m pip install .`, then run from another directory)
- [ ] Open zenodo, start new version, reserve DOI (currently at the top of Basic Information)
- [ ] New branch (burnman-Major.Minor)
- [ ] Bump version number in new branch (in burnman/version.py)
- [ ] Update changelog.txt with major changes since the last release.
- [ ] Update setup.py (if necessary, probably only Python versions need checking (as we've checked the installation works above), but might be worth checking that `sudo python setup.py sdist bdist_wheel` works without errors)
- [ ] Update new link to the zenodo version (using the new reserved DOI) in burnman/__init__.py
- [ ] Update new link to the zenodo version (using the new reserved DOI) in docs/index.rst
- [ ] Update new badge link to zenodo (using the new reserved DOI) in Readme.md
- [ ] Push new branch to Github upstream burnman-Major.Minor (*not* master)
- [ ] Make release on Github using upstream burnman-Major.Minor branch
- [ ] Make release commit (tag, not branch) active on readthedocs (you'll need to build from master first so that ReadTheDocs finds the new release tag)
- [ ] Build documentation on readthedocs
- [ ] Download zip file
- [ ] Upload new zip file to zenodo, fill in details on website (including new link to ReadTheDocs)
- [ ] Save and publish in zenodo
- [ ] Update GitHub release with new zip files and link to the ReadTheDocs documentation
- [ ] Push release to Pypi (from clean directory):
 1) sudo python setup.py sdist bdist_wheel (sudo unfortunately required)
 2) twine check dist/* (to check zip and wheel)
 3) twine upload --repository-url https://test.pypi.org/legacy/ dist/* (to test upload, can get password from the pypi website)
 4) twine upload dist/* (the final upload to Pypi)
- [ ] Merge upstream burnman-Major.Minor branch to master
- [ ] Bump version numbers in version.py on upstream master 
 - version=[Major].[Minor+1].0pre
 - short_version=[Major].[Minor+1].0
- [ ] Check and update homepage (especially the downloads section and the zenodo links)
